### PR TITLE
Fix immutable attribute validation.

### LINKED ISSUE #108: attributes mutability issue
Defining attribute as schema.AttributeMutabilityImmutable() doesn't work:
I created a user schema with the userName attribute as immutable so it can only be entered when creating a user, after performing a POST request I got the following error: `{“schemas”:[“urn:ietf:params:scim:api:messages:2.0:Error”],“scimType”:“mutability”,“detail”:“The attempted modification is not compatible with the target attribute’s mutability or current state.“,”status”:“400”}`

i think the issue is at [resource_type.go validate function](https://github.com/elimity-com/scim/blob/master/resource_type.go#L63) where the switch case should have been `case http.MethodPost, http.MethodPut:` and not `case http.MethodGet, http.MethodPut:`

### PR DESCRIPTION
**Pull request by di-wu**
Closes #108 

> **immutable** The attribute MAY be defined at resource creation (e.g., POST) or at record replacement via a request (e.g., a PUT).  The attribute SHALL NOT be updated.
[RFC 7643, Section 7](https://tools.ietf.org/html/rfc7643#section-7)

https://github.com/elimity-com/scim/blob/acfc5ea615ab446d3665677b1568de0f02aee359/schema/schema.go#L40-L44

Thank you @brumer for reporting this.

### CODE REVIEW

File: resource_type.go [hunk 1]
```diff
@@ -60,7 +60,7 @@ func (t ResourceType) validate(raw []byte, method string) (ResourceAttributes, *
 	var attributes map[string]interface{}
 	var scimErr *errors.ScimError
 	switch method {
-	case http.MethodGet, http.MethodPut:
+	case http.MethodPost, http.MethodPut:
```
Comment (jdeflander) [inline resource_type.go:63]: Is the `validate` method even called with methods other than `POST` and `PUT`?

Comment (di-wu) [reply resource_type.go:63]: No, it is not.

Comment (jdeflander) [reply resource_type.go:63]: > No, it is not.

Maybe we can just leave the `switch` out in that case?

**Review by jdeflander — APPROVED** [review]
